/**
 * 1. CONFIGURATION & GLOBAL STATE
 */

// Initialize the 3D Globe with performance-optimized settings
const viewer = new Cesium.Viewer("cesiumContainer", {
    // Use OpenStreetMap tiles to avoid needing a Google/Bing API key
    baseLayer: new Cesium.ImageryLayer(new Cesium.OpenStreetMapImageryProvider({ url: "https://a.tile.openstreetmap.org/" })),
    // Disable unnecessary UI widgets to keep the interface clean
    geocoder: false, 
    homeButton: false, 
    sceneModePicker: false, 
    navigationHelpButton: false, 
    animation: false, 
    timeline: false
});

// Temporary storage for events at a clicked location (needed for the search filter)
let currentClusterEvents = [];

// Color palette for the categories extracted by the Python scraper
const CATEGORIES = {
    "Conflict": "#e74c3c", // Red
    "Politics": "#8e44ad", // Purple
    "Science": "#2980b9",  // Blue
    "Sports": "#27ae60",   // Green
    "Culture": "#f39c12",  // Orange
    "General": "#7f8c8d"   // Gray
};

/**
 * 2. SIDEBAR & UI FUNCTIONS
 */

// Generates the HTML cards for the sidebar list
function renderEventList(events) {
    const content = document.getElementById('sidebarContent');
    content.innerHTML = events.map(e => `
        <div class="event-card" style="border-left: 5px solid ${CATEGORIES[e.category] || CATEGORIES.General}">
            <small style="font-weight: bold; color: ${CATEGORIES[e.category] || CATEGORIES.General}">
                ${e.category.toUpperCase()}
            </small>
            <h4 style="margin: 5px 0;">${e.title}</h4>
            <div style="font-size: 12px; margin-bottom: 8px;">📅 ${e.date}</div>
            <p style="font-size: 13px; line-height: 1.4;">${e.description}</p>
            <a href="${e.wikiLink}" target="_blank" style="font-size: 13px; color: #0066cc;">Wikipedia ↗</a>
        </div>
    `).join('');
}

// Opens the sidebar and populates it with events from a specific map pin
function showClusterMenu(events) {
    currentClusterEvents = events;
    document.getElementById('eventSidebar').style.display = 'block';
    document.getElementById('eventSearch').value = ''; // Clear previous searches
    renderEventList(events);
}

// Filters the visible list in the sidebar based on user text input
window.filterEvents = function() {
    const term = document.getElementById('eventSearch').value.toLowerCase();
    const filtered = currentClusterEvents.filter(e => 
        e.title.toLowerCase().includes(term) || e.description.toLowerCase().includes(term)
    );
    renderEventList(filtered);
};

/**
 * 3. DATA LOADING & CLUSTERING LOGIC
 */

window.loadHistoryYear = async function (year) {
    try {
        // Fetch the JSON file generated by your Scraper
        const response = await fetch(`./data/${year}.json`);
        if (!response.ok) return;
        const events = await response.json();
        
        // Clear all existing pins before loading new ones
        viewer.entities.removeAll();

        // --- CLUSTERING LOGIC ---
        // We group events by rounding their Lat/Lon to 2 decimal places.
        // This ensures that events in the same city (but slightly different coords)
        // are treated as a single "stack" on the map.
        const clusters = {};
        events.forEach(e => {
            const key = `${e.lat.toFixed(2)},${e.lon.toFixed(2)}`;
            if (!clusters[key]) clusters[key] = [];
            clusters[key].push(e);
        });

        // Loop through each unique coordinate group and create a Map Pin (Entity)
        Object.keys(clusters).forEach(key => {
            const evs = clusters[key];
            const isCluster = evs.length > 1;
            
            // If it's a cluster, make it Gold. If single, use category color.
            const color = isCluster ? 
                Cesium.Color.GOLD : 
                Cesium.Color.fromCssColorString(CATEGORIES[evs[0].category] || CATEGORIES.General);

            viewer.entities.add({
                position: Cesium.Cartesian3.fromDegrees(evs[0].lon, evs[0].lat),
                // IMPORTANT: We store the full array of events INSIDE the entity 
                // so we can retrieve them when the user clicks the pin.
                properties: { events: evs },
                point: { 
                    pixelSize: isCluster ? 18 : 10, // Larger dots for clusters
                    color: color, 
                    outlineColor: Cesium.Color.WHITE, 
                    outlineWidth: 2 
                },
                label: { 
                    text: isCluster ? evs.length.toString() : "", // Show count on clusters
                    font: '10px bold sans-serif',
                    disableDepthTestDistance: Number.POSITIVE_INFINITY // Prevents label from hiding behind terrain
                },
                // If it's a single event, use the standard Cesium popup. 
                // If it's a cluster, we leave description undefined and use our custom Sidebar instead.
                description: !isCluster ? `
                    <div style="padding:10px;">
                        <strong>${evs[0].date}</strong><br/><br/>
                        ${evs[0].description}<br/><br/>
                        <a href="${evs[0].wikiLink}" target="_blank">Wikipedia Article</a>
                    </div>` : undefined
            });
        });
    } catch (e) { console.error("Error loading year data:", e); }
};

/**
 * 4. INTERACTION HANDLER
 */

// Listen for clicks on the globe
new Cesium.ScreenSpaceEventHandler(viewer.scene.canvas).setInputAction((click) => {
    // Check if the user clicked on a Pin (Entity)
    const picked = viewer.scene.pick(click.position);
    
    if (Cesium.defined(picked) && picked.id.properties) {
        // Retrieve the events we "hid" in the properties earlier
        const evs = picked.id.properties.events.getValue();
        
        // If there is more than 1 event at this spot, trigger our custom Sidebar
        if (evs.length > 1) {
            showClusterMenu(evs);
            // Prevent Cesium from showing its default empty infoBox for clusters
            viewer.selectedEntity = undefined;
        }
    }
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
